# TCL File Generated by Component Editor 11.1sp2
# Tue Apr 16 17:51:16 BRT 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sv_packet_processor "sv_packet_processor" v1.0
# | null 2013.04.16.17:51:16
# | 
# | 
# | C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/sv_packet_processor/sv_packet_processor.vhd
# | 
# |    ./sv_packet_processor.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module sv_packet_processor
# | 
set_module_property NAME sv_packet_processor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME sv_packet_processor
set_module_property TOP_LEVEL_HDL_FILE sv_packet_processor.vhd
set_module_property TOP_LEVEL_HDL_MODULE sv_packet_processor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME sv_packet_processor
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sv_packet_processor.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter ERROR_LENGTH NATURAL 1
set_parameter_property ERROR_LENGTH DEFAULT_VALUE 1
set_parameter_property ERROR_LENGTH DISPLAY_NAME ERROR_LENGTH
set_parameter_property ERROR_LENGTH TYPE NATURAL
set_parameter_property ERROR_LENGTH UNITS None
set_parameter_property ERROR_LENGTH ALLOWED_RANGES 0:2147483647
set_parameter_property ERROR_LENGTH AFFECTS_GENERATION false
set_parameter_property ERROR_LENGTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 1
set_interface_property avalon_slave_0 writeWaitTime 1

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input 8
add_interface_port avalon_slave_0 byteenable byteenable Input 4
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source
# | 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_sink
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0

set_interface_property avalon_streaming_source ENABLED true

add_interface_port avalon_streaming_source source_ready ready Input 1
add_interface_port avalon_streaming_source source_valid valid Output 1
add_interface_port avalon_streaming_source source_data data Output 32
add_interface_port avalon_streaming_source source_empty empty Output 2
add_interface_port avalon_streaming_source source_sop startofpacket Output 1
add_interface_port avalon_streaming_source source_eop endofpacket Output 1
add_interface_port avalon_streaming_source source_err error Output error_length
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end protection_analog_data_input export Input 512
add_interface_port conduit_end protection_analog_data_ready export Input 1
add_interface_port conduit_end monitoring_analog_data_input export Input 512
add_interface_port conduit_end monitoring_analog_data_ready export Input 1
add_interface_port conduit_end monitoring_analog_new_data export Output 1
add_interface_port conduit_end pps export Input 1
add_interface_port conduit_end sysclk export Input 1
add_interface_port conduit_end irig_status export Input 8
# | 
# +-----------------------------------
