# TCL File Generated by Component Editor 11.0sp1
# Wed Jun 13 11:06:18 BRT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | inter_eth "inter_eth" v1.0
# | null 2012.06.13.11:06:18
# | 
# | 
# | C:/work/produtos/MU320/SVN/gateware/de2_115/rtl/vhdl/inter_eth/inter_eth.vhd
# | 
# |    ./inter_eth.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module inter_eth
# | 
set_module_property NAME inter_eth
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME inter_eth
set_module_property TOP_LEVEL_HDL_FILE inter_eth.vhd
set_module_property TOP_LEVEL_HDL_MODULE inter_eth
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME inter_eth
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file inter_eth.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter SYMBOLS_PER_BEAT NATURAL 4
set_parameter_property SYMBOLS_PER_BEAT DEFAULT_VALUE 4
set_parameter_property SYMBOLS_PER_BEAT DISPLAY_NAME SYMBOLS_PER_BEAT
set_parameter_property SYMBOLS_PER_BEAT TYPE NATURAL
set_parameter_property SYMBOLS_PER_BEAT UNITS None
set_parameter_property SYMBOLS_PER_BEAT ALLOWED_RANGES 0:2147483647
set_parameter_property SYMBOLS_PER_BEAT AFFECTS_GENERATION false
set_parameter_property SYMBOLS_PER_BEAT HDL_PARAMETER true
add_parameter BITS_PER_SYMBOL NATURAL 8
set_parameter_property BITS_PER_SYMBOL DEFAULT_VALUE 8
set_parameter_property BITS_PER_SYMBOL DISPLAY_NAME BITS_PER_SYMBOL
set_parameter_property BITS_PER_SYMBOL TYPE NATURAL
set_parameter_property BITS_PER_SYMBOL UNITS None
set_parameter_property BITS_PER_SYMBOL ALLOWED_RANGES 0:2147483647
set_parameter_property BITS_PER_SYMBOL AFFECTS_GENERATION false
set_parameter_property BITS_PER_SYMBOL HDL_PARAMETER true
add_parameter READY_LATENCY NATURAL 0
set_parameter_property READY_LATENCY DEFAULT_VALUE 0
set_parameter_property READY_LATENCY DISPLAY_NAME READY_LATENCY
set_parameter_property READY_LATENCY TYPE NATURAL
set_parameter_property READY_LATENCY UNITS None
set_parameter_property READY_LATENCY ALLOWED_RANGES 0:2147483647
set_parameter_property READY_LATENCY AFFECTS_GENERATION false
set_parameter_property READY_LATENCY HDL_PARAMETER true
add_parameter ERROR_LENGTH NATURAL 1
set_parameter_property ERROR_LENGTH DEFAULT_VALUE 1
set_parameter_property ERROR_LENGTH DISPLAY_NAME ERROR_LENGTH
set_parameter_property ERROR_LENGTH TYPE NATURAL
set_parameter_property ERROR_LENGTH UNITS None
set_parameter_property ERROR_LENGTH ALLOWED_RANGES 0:2147483647
set_parameter_property ERROR_LENGTH AFFECTS_GENERATION false
set_parameter_property ERROR_LENGTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink sysclk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink
# | 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_sink
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0

set_interface_property avalon_streaming_sink ENABLED true

add_interface_port avalon_streaming_sink sink_dma_ready ready Output 1
add_interface_port avalon_streaming_sink sink_dma_valid valid Input 1
add_interface_port avalon_streaming_sink sink_dma_data data Input 32
add_interface_port avalon_streaming_sink sink_dma_empty empty Input 2
add_interface_port avalon_streaming_sink sink_dma_sop startofpacket Input 1
add_interface_port avalon_streaming_sink sink_dma_eop endofpacket Input 1
add_interface_port avalon_streaming_sink sink_dma_err error Input error_length
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source
# | 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock_sink
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0

set_interface_property avalon_streaming_source ENABLED true

add_interface_port avalon_streaming_source source_ready ready Input 1
add_interface_port avalon_streaming_source source_data data Output 32
add_interface_port avalon_streaming_source source_valid valid Output 1
add_interface_port avalon_streaming_source source_empty empty Output 2
add_interface_port avalon_streaming_source source_sop startofpacket Output 1
add_interface_port avalon_streaming_source source_eop endofpacket Output 1
add_interface_port avalon_streaming_source source_err error Output error_length
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink_1
# | 
add_interface avalon_streaming_sink_1 avalon_streaming end
set_interface_property avalon_streaming_sink_1 associatedClock clock_sink
set_interface_property avalon_streaming_sink_1 associatedReset reset
set_interface_property avalon_streaming_sink_1 dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_1 errorDescriptor ""
set_interface_property avalon_streaming_sink_1 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_1 maxChannel 0
set_interface_property avalon_streaming_sink_1 readyLatency 0

set_interface_property avalon_streaming_sink_1 ENABLED true

add_interface_port avalon_streaming_sink_1 sink_analog_ready ready Output 1
add_interface_port avalon_streaming_sink_1 sink_analog_valid valid Input 1
add_interface_port avalon_streaming_sink_1 sink_analog_empty empty Input 2
add_interface_port avalon_streaming_sink_1 sink_analog_data data Input 32
add_interface_port avalon_streaming_sink_1 sink_analog_sop startofpacket Input 1
add_interface_port avalon_streaming_sink_1 sink_analog_eop endofpacket Input 1
add_interface_port avalon_streaming_sink_1 sink_analog_err error Input error_length
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end hold_counter export Input 4
# | 
# +-----------------------------------
