# TCL File Generated by Component Editor 12.1
# Tue Jul 09 16:10:10 BRT 2013
# DO NOT MODIFY


# 
# watchdog_timeout_counter "watchdog_timeout_counter" v1.0
# null 2013.07.09.16:10:10
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module watchdog_timeout_counter
# 
set_module_property NAME watchdog_timeout_counter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME watchdog_timeout_counter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL watchdog_timeout_counter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS true
add_fileset_file watchdog_timeout_counter.vhd VHDL PATH watchdog_timeout_counter.vhd
add_fileset_file neg_edge_moore.vhd VHDL PATH neg_edge_moore.vhd


# 
# parameters
# 
add_parameter FREQ_MHZ INTEGER 25
set_parameter_property FREQ_MHZ DEFAULT_VALUE 25
set_parameter_property FREQ_MHZ DISPLAY_NAME FREQ_MHZ
set_parameter_property FREQ_MHZ TYPE INTEGER
set_parameter_property FREQ_MHZ UNITS None
set_parameter_property FREQ_MHZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FREQ_MHZ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avs_cpu
# 
add_interface avs_cpu avalon end
set_interface_property avs_cpu addressUnits WORDS
set_interface_property avs_cpu associatedClock clock
set_interface_property avs_cpu associatedReset reset_cpu
set_interface_property avs_cpu bitsPerSymbol 8
set_interface_property avs_cpu burstOnBurstBoundariesOnly false
set_interface_property avs_cpu burstcountUnits WORDS
set_interface_property avs_cpu explicitAddressSpan 0
set_interface_property avs_cpu holdTime 0
set_interface_property avs_cpu linewrapBursts false
set_interface_property avs_cpu maximumPendingReadTransactions 0
set_interface_property avs_cpu readLatency 0
set_interface_property avs_cpu readWaitTime 1
set_interface_property avs_cpu setupTime 0
set_interface_property avs_cpu timingUnits Cycles
set_interface_property avs_cpu writeWaitStates 1
set_interface_property avs_cpu writeWaitTime 1
set_interface_property avs_cpu ENABLED true

add_interface_port avs_cpu avs_address address Input 1
add_interface_port avs_cpu avs_chipselect chipselect Input 1
add_interface_port avs_cpu avs_read read Input 1
add_interface_port avs_cpu avs_readdata readdata Output 32
set_interface_assignment avs_cpu embeddedsw.configuration.isFlash 0
set_interface_assignment avs_cpu embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_cpu embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_cpu embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset_cpu
# 
add_interface reset_cpu reset end
set_interface_property reset_cpu associatedClock clock
set_interface_property reset_cpu synchronousEdges DEASSERT
set_interface_property reset_cpu ENABLED true

add_interface_port reset_cpu reset_n reset_n Input 1


# 
# connection point reset_watchdog
# 
add_interface reset_watchdog reset end
set_interface_property reset_watchdog associatedClock clock
set_interface_property reset_watchdog synchronousEdges DEASSERT
set_interface_property reset_watchdog ENABLED true

add_interface_port reset_watchdog rsi_watchdog_n reset_n Input 1

