# TCL File Generated by Component Editor 11.1sp2
# Tue May 14 14:30:49 BRT 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | nom_freq_sel "nom_freq_sel" v1.0
# | null 2013.05.14.14:30:49
# | 
# | 
# | C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/nom_freq_sel/nom_freq_sel.vhd
# | 
# |    ./nom_freq_sel.vhd syn, sim
# |    ./C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/mu320_constants.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module nom_freq_sel
# | 
set_module_property NAME nom_freq_sel
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME nom_freq_sel
set_module_property TOP_LEVEL_HDL_FILE nom_freq_sel.vhd
set_module_property TOP_LEVEL_HDL_MODULE nom_freq_sel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME nom_freq_sel
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file nom_freq_sel.vhd {SYNTHESIS SIMULATION}
add_file C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/mu320_constants.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 1
set_interface_property avalon_slave_0 writeWaitTime 1

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 avs_address address Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_chipselect chipselect Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end freq_80_o export Output 13
add_interface_port conduit_end step_low_80_o export Output 7
add_interface_port conduit_end step_normal_80_o export Output 14
add_interface_port conduit_end freq_default_std_80_o export Output 60
add_interface_port conduit_end k_default_std_80_o export Output 44
add_interface_port conduit_end freq_256_o export Output 14
add_interface_port conduit_end step_low_256_o export Output 2
add_interface_port conduit_end step_normal_256_o export Output 3
add_interface_port conduit_end freq_default_std_256_o export Output 60
add_interface_port conduit_end k_default_std_256_o export Output 44
add_interface_port conduit_end sync_reset_o_n export Output 1
add_interface_port conduit_end sysclk export Input 1
# | 
# +-----------------------------------
