# TCL File Generated by Component Editor 10.1sp1
# Sat Feb 26 15:26:31 EST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | chu_avalon_sram "chu_avalon_sram" v1.0
# |  2011.02.26.15:26:31
# | DE1 SRAM controller
# | 
# | K:/code/chu_ip_v101/chu_avalon_sram/chu_avalon_sram.vhd
# | 
# |    ./chu_avalon_sram.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module chu_avalon_sram
# | 
set_module_property DESCRIPTION "DE1 SRAM controller"
set_module_property NAME chu_avalon_sram
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP chu_ip
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME chu_avalon_sram
set_module_property TOP_LEVEL_HDL_FILE chu_avalon_sram.vhd
set_module_property TOP_LEVEL_HDL_MODULE chu_avalon_sram
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file chu_avalon_sram.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset clockRate 0

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset_reset
# | 
add_interface clock_reset_reset reset end
set_interface_property clock_reset_reset associatedClock clock_reset
set_interface_property clock_reset_reset synchronousEdges DEASSERT

set_interface_property clock_reset_reset ENABLED true

add_interface_port clock_reset_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point cpu_ctrl
# | 
add_interface cpu_ctrl avalon end
set_interface_property cpu_ctrl addressAlignment DYNAMIC
set_interface_property cpu_ctrl addressUnits WORDS
set_interface_property cpu_ctrl associatedClock clock_reset
set_interface_property cpu_ctrl associatedReset clock_reset_reset
set_interface_property cpu_ctrl burstOnBurstBoundariesOnly false
set_interface_property cpu_ctrl explicitAddressSpan 0
set_interface_property cpu_ctrl holdTime 0
set_interface_property cpu_ctrl isMemoryDevice true
set_interface_property cpu_ctrl isNonVolatileStorage false
set_interface_property cpu_ctrl linewrapBursts false
set_interface_property cpu_ctrl maximumPendingReadTransactions 0
set_interface_property cpu_ctrl printableDevice false
set_interface_property cpu_ctrl readLatency 2
set_interface_property cpu_ctrl readWaitStates 0
set_interface_property cpu_ctrl readWaitTime 0
set_interface_property cpu_ctrl setupTime 0
set_interface_property cpu_ctrl timingUnits Cycles
set_interface_property cpu_ctrl writeWaitTime 0

set_interface_property cpu_ctrl ENABLED true

add_interface_port cpu_ctrl address address Input 18
add_interface_port cpu_ctrl writedata writedata Input 16
add_interface_port cpu_ctrl readdata readdata Output 16
add_interface_port cpu_ctrl chipselect_n chipselect_n Input 1
add_interface_port cpu_ctrl byteenable_n byteenable_n Input 2
add_interface_port cpu_ctrl read_n read_n Input 1
add_interface_port cpu_ctrl write_n write_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ctrl_sram
# | 
add_interface ctrl_sram conduit end

set_interface_property ctrl_sram ENABLED true

add_interface_port ctrl_sram sram_dq export Bidir 16
add_interface_port ctrl_sram sram_ce_n export Output 1
add_interface_port ctrl_sram sram_lb_n export Output 1
add_interface_port ctrl_sram sram_ub_n export Output 1
add_interface_port ctrl_sram sram_oe_n export Output 1
add_interface_port ctrl_sram sram_we_n export Output 1
add_interface_port ctrl_sram sram_addr export Output 18
# | 
# +-----------------------------------
