# TCL File Generated by Component Editor 11.1sp2
# Mon Feb 11 17:13:21 BRST 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | digital_register "digital_register" v1.0
# | null 2013.02.11.17:13:21
# | 
# | 
# | C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/digital_register/digital_register.vhd
# | 
# |    ./digital_register.vhd syn, sim
# |    ./C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/mu320_constants.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module digital_register
# | 
set_module_property NAME digital_register
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME digital_register
set_module_property TOP_LEVEL_HDL_FILE digital_register.vhd
set_module_property TOP_LEVEL_HDL_MODULE digital_register
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME digital_register
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file digital_register.vhd {SYNTHESIS SIMULATION}
add_file C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/mu320_constants.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point digital
# | 
add_interface digital avalon end
set_interface_property digital addressUnits WORDS
set_interface_property digital associatedClock clock_sink
set_interface_property digital associatedReset reset
set_interface_property digital bitsPerSymbol 8
set_interface_property digital burstOnBurstBoundariesOnly false
set_interface_property digital burstcountUnits WORDS
set_interface_property digital explicitAddressSpan 0
set_interface_property digital holdTime 0
set_interface_property digital linewrapBursts false
set_interface_property digital maximumPendingReadTransactions 0
set_interface_property digital readLatency 0
set_interface_property digital readWaitTime 1
set_interface_property digital setupTime 0
set_interface_property digital timingUnits Cycles
set_interface_property digital writeWaitStates 1
set_interface_property digital writeWaitTime 1

set_interface_property digital ENABLED true

add_interface_port digital digital_address address Input 2
add_interface_port digital digital_readdata readdata Output 32
add_interface_port digital digital_read read Input 1
add_interface_port digital digital_chipselect chipselect Input 1
add_interface_port digital digital_writedata writedata Input 32
add_interface_port digital digital_write write Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end data_input_available export Input 1
add_interface_port conduit_end sysclk export Input 1
add_interface_port conduit_end data_input export Input 32
add_interface_port conduit_end data_output export Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint digital
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset

set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender digital_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink digital_clk clk Input 1
# | 
# +-----------------------------------
