# TCL File Generated by Component Editor 12.1
# Tue Feb 25 10:24:37 BRT 2014
# DO NOT MODIFY


# 
# quality_top "quality_top" v1.0
# null 2014.02.25.10:24:37
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module quality_top
# 
set_module_property NAME quality_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME quality_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL quality_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mu320_constants.vhd VHDL PATH ../mu320_constants.vhd
add_fileset_file gate_soft_interface.vhd VHDL PATH gate_soft_interface.vhd
add_fileset_file quality_top.vhd VHDL PATH quality_top.vhd
add_fileset_file signal_align.vhd VHDL PATH signal_align.vhd
add_fileset_file main_fsm.vhd VHDL PATH main_fsm.vhd
add_fileset_file quality_decoder.vhd VHDL PATH quality_decoder.vhd 
add_fileset_file quality_decoder.vhd VHDL PATH quality_insert.vhd 


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitStates 1
set_interface_property avalon_slave_0 writeWaitTime 1
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_address address Input 3
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_chipselect chipselect Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clock
set_interface_property conduit_end_0 associatedReset ""
set_interface_property conduit_end_0 ENABLED true

add_interface_port conduit_end_0 coe_sysclk export Input 1
add_interface_port conduit_end_0 coe_acq_bus_i export Input 8
add_interface_port conduit_end_0 coe_gain_bus_i export Input 8
add_interface_port conduit_end_0 coe_ps_bus_i export Input 4
add_interface_port conduit_end_0 coe_phase_sum_ready_i export Input 1 
add_interface_port conduit_end_0 coe_sample_values_i export Input 256
add_interface_port conduit_end_0 coe_sample_values_o export Output 512
add_interface_port conduit_end_0 coe_sv_ready_o export Output 1 

