--------------------------------------------------------------------------------
-- Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____ 
--  /   /\/   / 
-- /___/  \  /    Vendor: Xilinx 
-- \   \   \/     Version : 14.1
--  \   \         Application : xaw2vhdl
--  /   /         Filename : CLK_GEN.vhd
-- /___/   /\     Timestamp : 03/05/2014 14:29:23
-- \   \  /  \ 
--  \___\/\___\ 
--
--Command: xaw2vhdl-intstyle M:/Projetos/VHDL/L_Test_Rig/Ejector_Board/EJECTORS_TEST_V01/ipcore_dir/CLK_GEN.xaw -st CLK_GEN.vhd
--Design Name: CLK_GEN
--Device: xc3s200-4tq144
--
-- Module CLK_GEN
-- Generated by Xilinx Architecture Wizard
-- Written for synthesis tool: XST
-- Period Jitter (unit interval) for block DCM_INST = 0.03 UI
-- Period Jitter (Peak-to-Peak) for block DCM_INST = 1.00 ns

library ieee;
use ieee.std_logic_1164.ALL;
use ieee.numeric_std.ALL;
library UNISIM;
use UNISIM.Vcomponents.ALL;

entity CLK_GEN is
   port ( CE_IN           : in    std_logic; 
          CLKIN_IN        : in    std_logic; 
          CLR_IN          : in    std_logic; 
          PRE_IN          : in    std_logic; 
          RST_IN          : in    std_logic; 
          CLKFX_OUT       : out   std_logic; 
          CLKIN_IBUFG_OUT : out   std_logic; 
          CLK0_OUT        : out   std_logic; 
          DDR_CLKFX_OUT   : out   std_logic; 
          LOCKED_OUT      : out   std_logic);
end CLK_GEN;

architecture BEHAVIORAL of CLK_GEN is
   signal CLKFB_IN        : std_logic;
   signal CLKFX_BUF       : std_logic;
   signal CLKFX_INV_IN    : std_logic;
   signal CLKIN_IBUFG     : std_logic;
   signal CLK0_BUF        : std_logic;
   signal C0_IN           : std_logic;
   signal GND_BIT         : std_logic;
   signal VCC_BIT         : std_logic;
begin
   GND_BIT <= '0';
   VCC_BIT <= '1';
   CLKFX_OUT <= C0_IN;
   CLKIN_IBUFG_OUT <= CLKIN_IBUFG;
   CLK0_OUT <= CLKFB_IN;
   CLKFX_BUFG_INST : BUFG
      port map (I=>CLKFX_BUF,
                O=>C0_IN);
   
   CLKIN_IBUFG_INST : IBUFG
      port map (I=>CLKIN_IN,
                O=>CLKIN_IBUFG);
   
   CLK0_BUFG_INST : BUFG
      port map (I=>CLK0_BUF,
                O=>CLKFB_IN);
   
   DCM_INST : DCM
   generic map( CLK_FEEDBACK => "1X",
            CLKDV_DIVIDE => 2.0,
            CLKFX_DIVIDE => 5,
            CLKFX_MULTIPLY => 4,
            CLKIN_DIVIDE_BY_2 => FALSE,
            CLKIN_PERIOD => 26.667,
            CLKOUT_PHASE_SHIFT => "NONE",
            DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS",
            DFS_FREQUENCY_MODE => "LOW",
            DLL_FREQUENCY_MODE => "LOW",
            DUTY_CYCLE_CORRECTION => TRUE,
            FACTORY_JF => x"8080",
            PHASE_SHIFT => 0,
            STARTUP_WAIT => FALSE)
      port map (CLKFB=>CLKFB_IN,
                CLKIN=>CLKIN_IBUFG,
                DSSEN=>GND_BIT,
                PSCLK=>GND_BIT,
                PSEN=>GND_BIT,
                PSINCDEC=>GND_BIT,
                RST=>RST_IN,
                CLKDV=>open,
                CLKFX=>CLKFX_BUF,
                CLKFX180=>open,
                CLK0=>CLK0_BUF,
                CLK2X=>open,
                CLK2X180=>open,
                CLK90=>open,
                CLK180=>open,
                CLK270=>open,
                LOCKED=>LOCKED_OUT,
                PSDONE=>open,
                STATUS=>open);
   
   INV_INST : INV
      port map (I=>C0_IN,
                O=>CLKFX_INV_IN);
   
   OFDDRCPE_INST : OFDDRCPE
      port map (CE=>CE_IN,
                CLR=>CLR_IN,
                C0=>C0_IN,
                C1=>CLKFX_INV_IN,
                D0=>VCC_BIT,
                D1=>GND_BIT,
                PRE=>PRE_IN,
                Q=>DDR_CLKFX_OUT);
   
end BEHAVIORAL;


