# TCL File Generated by Component Editor 11.1sp2
# Wed May 08 12:08:33 BRT 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | st_channel_adapter "st_channel_adapter" v1.0
# | null 2013.05.08.12:08:33
# | 
# | 
# | C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/st_channel_adapter/st_channel_adapter.vhd
# | 
# |    ./st_channel_adapter.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module st_channel_adapter
# | 
set_module_property NAME st_channel_adapter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME st_channel_adapter
set_module_property TOP_LEVEL_HDL_FILE st_channel_adapter.vhd
set_module_property TOP_LEVEL_HDL_MODULE st_channel_adapter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME st_channel_adapter
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file st_channel_adapter.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter CHANNEL_LENGTH NATURAL 0
set_parameter_property CHANNEL_LENGTH DEFAULT_VALUE 0
set_parameter_property CHANNEL_LENGTH DISPLAY_NAME CHANNEL_LENGTH
set_parameter_property CHANNEL_LENGTH TYPE NATURAL
set_parameter_property CHANNEL_LENGTH UNITS None
set_parameter_property CHANNEL_LENGTH ALLOWED_RANGES 0:2147483647
set_parameter_property CHANNEL_LENGTH AFFECTS_GENERATION false
set_parameter_property CHANNEL_LENGTH HDL_PARAMETER true
add_parameter ERROR_LENGTH NATURAL 1
set_parameter_property ERROR_LENGTH DEFAULT_VALUE 1
set_parameter_property ERROR_LENGTH DISPLAY_NAME ERROR_LENGTH
set_parameter_property ERROR_LENGTH TYPE NATURAL
set_parameter_property ERROR_LENGTH UNITS None
set_parameter_property ERROR_LENGTH ALLOWED_RANGES 0:2147483647
set_parameter_property ERROR_LENGTH AFFECTS_GENERATION false
set_parameter_property ERROR_LENGTH HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink_0
# | 
add_interface avalon_streaming_sink_0 avalon_streaming end
set_interface_property avalon_streaming_sink_0 associatedClock clock_sink
set_interface_property avalon_streaming_sink_0 associatedReset reset
set_interface_property avalon_streaming_sink_0 dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink_0 errorDescriptor ""
set_interface_property avalon_streaming_sink_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink_0 maxChannel 3
set_interface_property avalon_streaming_sink_0 readyLatency 0

set_interface_property avalon_streaming_sink_0 ENABLED true

add_interface_port avalon_streaming_sink_0 asi_ready ready Output 1
add_interface_port avalon_streaming_sink_0 asi_valid valid Input 1
add_interface_port avalon_streaming_sink_0 asi_data data Input 32
add_interface_port avalon_streaming_sink_0 asi_channel channel Input channel_length
add_interface_port avalon_streaming_sink_0 asi_error error Input error_length
add_interface_port avalon_streaming_sink_0 asi_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink_0 asi_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink_0 asi_empty empty Input 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_source_0
# | 
add_interface avalon_streaming_source_0 avalon_streaming start
set_interface_property avalon_streaming_source_0 associatedClock clock_sink
set_interface_property avalon_streaming_source_0 associatedReset reset
set_interface_property avalon_streaming_source_0 dataBitsPerSymbol 8
set_interface_property avalon_streaming_source_0 errorDescriptor ""
set_interface_property avalon_streaming_source_0 firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source_0 maxChannel 0
set_interface_property avalon_streaming_source_0 readyLatency 0

set_interface_property avalon_streaming_source_0 ENABLED true

add_interface_port avalon_streaming_source_0 aso_ready ready Input 1
add_interface_port avalon_streaming_source_0 aso_valid valid Output 1
add_interface_port avalon_streaming_source_0 aso_data data Output 32
add_interface_port avalon_streaming_source_0 aso_error error Output error_length
add_interface_port avalon_streaming_source_0 aso_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source_0 aso_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source_0 aso_empty empty Output 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink sysclk clk Input 1
# | 
# +-----------------------------------
