# TCL File Generated by Component Editor 11.1sp2
# Fri Jun 28 11:09:56 BRT 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | phase_sum "phase_sum" v1.0
# | null 2013.06.28.11:09:56
# | 
# | 
# | C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/phase_sum/phase_sum.vhd
# | 
# |    ./phase_sum.vhd syn, sim
# |    ./C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/mu320_constants.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module phase_sum
# | 
set_module_property NAME phase_sum
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME phase_sum
set_module_property TOP_LEVEL_HDL_FILE phase_sum.vhd
set_module_property TOP_LEVEL_HDL_MODULE phase_sum
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME phase_sum
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file phase_sum.vhd {SYNTHESIS SIMULATION}
add_file C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/mu320_constants.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter N_CHANNELS_ANA_BOARD NATURAL 8
set_parameter_property N_CHANNELS_ANA_BOARD DEFAULT_VALUE 8
set_parameter_property N_CHANNELS_ANA_BOARD DISPLAY_NAME N_CHANNELS_ANA_BOARD
set_parameter_property N_CHANNELS_ANA_BOARD TYPE NATURAL
set_parameter_property N_CHANNELS_ANA_BOARD UNITS None
set_parameter_property N_CHANNELS_ANA_BOARD ALLOWED_RANGES 0:2147483647
set_parameter_property N_CHANNELS_ANA_BOARD AFFECTS_GENERATION false
set_parameter_property N_CHANNELS_ANA_BOARD HDL_PARAMETER true
add_parameter COE_IN_OUT_BITS NATURAL 128
set_parameter_property COE_IN_OUT_BITS DEFAULT_VALUE 128
set_parameter_property COE_IN_OUT_BITS DISPLAY_NAME COE_IN_OUT_BITS
set_parameter_property COE_IN_OUT_BITS TYPE NATURAL
set_parameter_property COE_IN_OUT_BITS UNITS None
set_parameter_property COE_IN_OUT_BITS ALLOWED_RANGES 0:2147483647
set_parameter_property COE_IN_OUT_BITS AFFECTS_GENERATION false
set_parameter_property COE_IN_OUT_BITS HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avs_cpu
# | 
add_interface avs_cpu avalon end
set_interface_property avs_cpu addressUnits WORDS
set_interface_property avs_cpu associatedClock clock
set_interface_property avs_cpu associatedReset reset
set_interface_property avs_cpu bitsPerSymbol 8
set_interface_property avs_cpu burstOnBurstBoundariesOnly false
set_interface_property avs_cpu burstcountUnits WORDS
set_interface_property avs_cpu explicitAddressSpan 0
set_interface_property avs_cpu holdTime 0
set_interface_property avs_cpu linewrapBursts false
set_interface_property avs_cpu maximumPendingReadTransactions 0
set_interface_property avs_cpu readLatency 0
set_interface_property avs_cpu readWaitTime 1
set_interface_property avs_cpu setupTime 0
set_interface_property avs_cpu timingUnits Cycles
set_interface_property avs_cpu writeWaitStates 1
set_interface_property avs_cpu writeWaitTime 1

set_interface_property avs_cpu ENABLED true

add_interface_port avs_cpu avs_read read Input 1
add_interface_port avs_cpu avs_address address Input 2
add_interface_port avs_cpu avs_chipselect chipselect Input 1
add_interface_port avs_cpu avs_write write Input 1
add_interface_port avs_cpu avs_writedata writedata Input 32
add_interface_port avs_cpu avs_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point data_io_board
# | 
add_interface data_io_board conduit end

set_interface_property data_io_board ENABLED true

add_interface_port data_io_board coe_data_input export Input coe_in_out_bits
add_interface_port data_io_board coe_data_output export Output coe_in_out_bits
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point data_ready_io
# | 
add_interface data_ready_io conduit end

set_interface_property data_ready_io ENABLED true

add_interface_port data_ready_io coe_data_ready_in export Input 1
add_interface_port data_ready_io coe_data_ready_out export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point sysclk
# | 
add_interface sysclk conduit end

set_interface_property sysclk ENABLED true

add_interface_port sysclk coe_sysclk export Input 1
# | 
# +-----------------------------------
