# TCL File Generated by Component Editor 11.1sp2
# Tue Jun 18 14:07:33 BRT 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | watchdog_instrument "watchdog_instrument" v1.0
# | null 2013.06.18.14:07:33
# | 
# | 
# | C:/work/produtos/MU320/SVN/gateware/mu320/rtl/vhdl/watchdog_instrument/watchdog_instrument.vhd
# | 
# |    ./watchdog_instrument.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module watchdog_instrument
# | 
set_module_property NAME watchdog_instrument
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME watchdog_instrument
set_module_property TOP_LEVEL_HDL_FILE watchdog_instrument.vhd
set_module_property TOP_LEVEL_HDL_MODULE watchdog_instrument
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME watchdog_instrument
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file watchdog_instrument.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter FREQ_MHZ INTEGER 25
set_parameter_property FREQ_MHZ DEFAULT_VALUE 25
set_parameter_property FREQ_MHZ DISPLAY_NAME FREQ_MHZ
set_parameter_property FREQ_MHZ TYPE INTEGER
set_parameter_property FREQ_MHZ UNITS None
set_parameter_property FREQ_MHZ ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FREQ_MHZ AFFECTS_GENERATION false
set_parameter_property FREQ_MHZ HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock sysclk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point coe_alarm
# | 
add_interface coe_alarm conduit end

set_interface_property coe_alarm ENABLED true

add_interface_port coe_alarm coe_alarm export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avs_cpu
# | 
add_interface avs_cpu avalon end
set_interface_property avs_cpu addressAlignment DYNAMIC
set_interface_property avs_cpu addressUnits WORDS
set_interface_property avs_cpu associatedClock clock
set_interface_property avs_cpu associatedReset reset_sink
set_interface_property avs_cpu burstOnBurstBoundariesOnly false
set_interface_property avs_cpu explicitAddressSpan 0
set_interface_property avs_cpu holdTime 0
set_interface_property avs_cpu isMemoryDevice false
set_interface_property avs_cpu isNonVolatileStorage false
set_interface_property avs_cpu linewrapBursts false
set_interface_property avs_cpu maximumPendingReadTransactions 0
set_interface_property avs_cpu printableDevice false
set_interface_property avs_cpu readLatency 0
set_interface_property avs_cpu readWaitTime 1
set_interface_property avs_cpu setupTime 0
set_interface_property avs_cpu timingUnits Cycles
set_interface_property avs_cpu writeWaitStates 1
set_interface_property avs_cpu writeWaitTime 1

set_interface_property avs_cpu ENABLED true

add_interface_port avs_cpu avs_read read Input 1
add_interface_port avs_cpu avs_address address Input 2
add_interface_port avs_cpu avs_chipselect chipselect Input 1
add_interface_port avs_cpu avs_write write Input 1
add_interface_port avs_cpu avs_writedata writedata Input 32
add_interface_port avs_cpu avs_readdata readdata Output 32
# | 
# +-----------------------------------
