# TCL File Generated by Component Editor 8.1
# Sun Jan 25 21:31:49 EST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | chu_avalon_gcd "chu_avalon_gcd" v1.0
# | null 2009.01.25.21:31:49
# | 
# | 
# | K:/code/nios/chu_ip/chu_avalon_gcd/hdl/chu_avalon_gcd.vhd
# | 
# |    ./chu_avalon_gcd.vhd syn, sim
# |    ./gcd_engine.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module chu_avalon_gcd
# | 
set_module_property NAME chu_avalon_gcd
set_module_property VERSION 1.0
set_module_property GROUP chu_ip
set_module_property DISPLAY_NAME chu_avalon_gcd
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.numeric_std.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE chu_avalon_gcd.vhd
set_module_property TOP_LEVEL_HDL_MODULE chu_avalon_gcd
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file chu_avalon_gcd.vhd {SYNTHESIS SIMULATION}
add_file gcd_engine.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point gcd
# | 
add_interface gcd avalon end
set_interface_property gcd addressAlignment DYNAMIC
set_interface_property gcd addressSpan 16
set_interface_property gcd bridgesToMaster ""
set_interface_property gcd burstOnBurstBoundariesOnly false
set_interface_property gcd holdTime 0
set_interface_property gcd isMemoryDevice false
set_interface_property gcd isNonVolatileStorage false
set_interface_property gcd linewrapBursts false
set_interface_property gcd maximumPendingReadTransactions 0
set_interface_property gcd minimumUninterruptedRunLength 1
set_interface_property gcd printableDevice false
set_interface_property gcd readLatency 0
set_interface_property gcd readWaitStates 0
set_interface_property gcd readWaitTime 0
set_interface_property gcd setupTime 0
set_interface_property gcd timingUnits Cycles
set_interface_property gcd writeWaitTime 0

set_interface_property gcd ASSOCIATED_CLOCK clock_reset

add_interface_port gcd gcd_address address Input 3
add_interface_port gcd gcd_chipselect chipselect Input 1
add_interface_port gcd gcd_write write Input 1
add_interface_port gcd gcd_writedata writedata Input 32
add_interface_port gcd gcd_readdata readdata Output 32
# | 
# +-----------------------------------
