# TCL File Generated by Component Editor 12.1
# Tue Nov 05 11:28:06 BRST 2013
# DO NOT MODIFY


# 
# phase_sum "phase_sum" v1.0
# null 2013.11.05.11:28:06
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module phase_sum
# 
set_module_property NAME phase_sum
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME phase_sum
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL phase_sum
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file phase_sum.vhd VHDL PATH phase_sum.vhd
add_fileset_file mu320_constants.vhd VHDL PATH ../mu320_constants.vhd
add_fileset_file mu320_constants.vhd VHDL PATH adder_ovf.vhd

add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl TOP_LEVEL phase_sum
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file phase_sum.vhd VHDL PATH phase_sum.vhd
add_fileset_file mu320_constants.vhd VHDL PATH ../mu320_constants.vhd
add_fileset_file mu320_constants.vhd VHDL PATH adder_ovf.vhd


# 
# parameters
# 
add_parameter N_CHANNELS_ANA_BOARD NATURAL 8
set_parameter_property N_CHANNELS_ANA_BOARD DEFAULT_VALUE 8
set_parameter_property N_CHANNELS_ANA_BOARD DISPLAY_NAME N_CHANNELS_ANA_BOARD
set_parameter_property N_CHANNELS_ANA_BOARD TYPE NATURAL
set_parameter_property N_CHANNELS_ANA_BOARD UNITS None
set_parameter_property N_CHANNELS_ANA_BOARD ALLOWED_RANGES 0:2147483647
set_parameter_property N_CHANNELS_ANA_BOARD HDL_PARAMETER true
add_parameter COE_IN_OUT_BITS NATURAL 256 ""
set_parameter_property COE_IN_OUT_BITS DEFAULT_VALUE 256
set_parameter_property COE_IN_OUT_BITS DISPLAY_NAME COE_IN_OUT_BITS
set_parameter_property COE_IN_OUT_BITS TYPE NATURAL
set_parameter_property COE_IN_OUT_BITS UNITS None
set_parameter_property COE_IN_OUT_BITS ALLOWED_RANGES 0:2147483647
set_parameter_property COE_IN_OUT_BITS DESCRIPTION ""
set_parameter_property COE_IN_OUT_BITS HDL_PARAMETER true
add_parameter N_BITS NATURAL 32 ""
set_parameter_property N_BITS DEFAULT_VALUE 32
set_parameter_property N_BITS DISPLAY_NAME N_BITS_ADC
set_parameter_property N_BITS TYPE NATURAL
set_parameter_property N_BITS UNITS None
set_parameter_property N_BITS ALLOWED_RANGES 0:2147483647
set_parameter_property N_BITS DESCRIPTION ""
set_parameter_property N_BITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avs_cpu
# 
add_interface avs_cpu avalon end
set_interface_property avs_cpu addressUnits WORDS
set_interface_property avs_cpu associatedClock clock
set_interface_property avs_cpu associatedReset reset
set_interface_property avs_cpu bitsPerSymbol 8
set_interface_property avs_cpu burstOnBurstBoundariesOnly false
set_interface_property avs_cpu burstcountUnits WORDS
set_interface_property avs_cpu explicitAddressSpan 0
set_interface_property avs_cpu holdTime 0
set_interface_property avs_cpu linewrapBursts false
set_interface_property avs_cpu maximumPendingReadTransactions 0
set_interface_property avs_cpu readLatency 0
set_interface_property avs_cpu readWaitTime 1
set_interface_property avs_cpu setupTime 0
set_interface_property avs_cpu timingUnits Cycles
set_interface_property avs_cpu writeWaitStates 1
set_interface_property avs_cpu writeWaitTime 1
set_interface_property avs_cpu ENABLED true

add_interface_port avs_cpu avs_address address Input 1
add_interface_port avs_cpu avs_chipselect chipselect Input 1
add_interface_port avs_cpu avs_write write Input 1
add_interface_port avs_cpu avs_writedata writedata Input 32
set_interface_assignment avs_cpu embeddedsw.configuration.isFlash 0
set_interface_assignment avs_cpu embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_cpu embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_cpu embeddedsw.configuration.isPrintableDevice 0


# 
# connection point data_io_board
# 
add_interface data_io_board conduit end
set_interface_property data_io_board associatedClock ""
set_interface_property data_io_board associatedReset ""
set_interface_property data_io_board ENABLED true

add_interface_port data_io_board coe_data_input export Input coe_in_out_bits
add_interface_port data_io_board coe_data_output export Output coe_in_out_bits


# 
# connection point data_ready_io
# 
add_interface data_ready_io conduit end
set_interface_property data_ready_io associatedClock ""
set_interface_property data_ready_io associatedReset ""
set_interface_property data_ready_io ENABLED true

add_interface_port data_ready_io coe_data_ready_in export Input 1
add_interface_port data_ready_io coe_data_ready_out export Output 1



# 
# connection point adder_ofv
# 
add_interface adder_ofv conduit end
set_interface_property adder_ofv associatedClock ""
set_interface_property adder_ofv associatedReset ""
set_interface_property adder_ofv ENABLED true

add_interface_port adder_ofv coe_phase_sum_ovf_o export Output 2

# 
# connection point sysclk
# 
add_interface sysclk conduit end
set_interface_property sysclk associatedClock ""
set_interface_property sysclk associatedReset ""
set_interface_property sysclk ENABLED true

add_interface_port sysclk coe_sysclk export Input 1

